apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  # namespace: my-namespace
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: jooankrah/udagram-frontend-image:v1
        ports:
        - containerPort: 8100