apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  # namespace: my-namespace
  labels:
    app: udagram-frontend
spec:
  selector:
    app: udagram-frontend
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 80
  type: LoadBalancer